version: 0.2

phases:
  build:
    commands: 
      - ls
      - pwd
      - npm install -g @angular/cli
      - ls
      - npm install
      - ls
      - ng build -c production
artifacts:
  files:
    - '*'
  base-directory: dist/mythngapp
  name: build-$(date +%Y-%m-%d)